### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by seriousfreezing** [Raik176/datapack-utils#1]
### Mod Version

0.1.3

### Minecraft Version

1.21.1

### Mod Loader

Fabric

### Describe the Bug

Crash occurs when starting the game.

### Game Logs

[crash-2024-12-09_19.12.11-client.txt](https://github.com/user-attachments/files/18068725/crash-2024-12-09_19.12.11-client.txt)
[crash-2024-12-09_19.12.51-client.txt](https://github.com/user-attachments/files/18068726/crash-2024-12-09_19.12.51-client.txt)

**Comment by Raik176** [comment]
Should be fixed in 0.1.4.

**Comment by seriousfreezing** [comment]
[crash-2024-12-09_20.29.36-client.txt](https://github.com/user-attachments/files/18069354/crash-2024-12-09_20.29.36-client.txt)
Not fixed :(

**Comment by Raik176** [comment]
Looks like a mod incompatibility then

Can you try with just datapack utils + fabric api?

**Comment by seriousfreezing** [comment]
[crash-2024-12-09_20.56.38-client.txt](https://github.com/user-attachments/files/18069545/crash-2024-12-09_20.56.38-client.txt)
Datapack Utils + Fabric API

**Comment by Raik176** [comment]
Tested multiple times outside of my dev env now (before i didn't) and it should work now.

**Comment by seriousfreezing** [comment]
It works perfectly now! Thank you!
